#!/usr/bin/env python3
"""
Generates the Vesper Cine monitoring LUTs: Apple Log (Rec.2020) -> Rec.709.

This is the exact transform the viewfinder applies in
android/app/src/main/cpp/shaders/render.comp (displayRec709), so footage
graded through these LUTs looks like it did on the phone:

  Apple Log -> scene-linear (Apple Log Profile White Paper inverse)
            -> Rec.2020 to Rec.709 primaries (3x3, clamp negatives)
            -> exposure 0.8 -> Narkowicz ACES filmic fit (18% grey ~ 0.19 display-linear)
            -> display encoding

Outputs (33^3, .cube):
  AppleLog_to_Rec709_Gamma24.cube  BT.1886 / gamma 2.4 — grading timelines (Resolve "Rec.709 Gamma 2.4")
  AppleLog_to_Rec709_sRGB.cube     sRGB — matches the phone viewfinder exactly

For grading from scratch you don't need these: Resolve, Premiere and FCP all
support Apple Log natively (Input Color Space = "Apple Log", gamut Rec.2020).

Usage:  python3 color_science/generate_applelog_lut.py [--size 65]
"""
import argparse
import math
import os

# Apple Log Profile White Paper (September 2023).
R0, RT, C = -0.05641088, 0.01, 47.28711236
BETA, GAMMA, DELTA = 0.00964052, 0.08550479, 0.69336945
YT = C * (RT - R0) ** 2  # code value at the linear/log joint (0.2085553)


def apple_log_encode(x):
    if x >= RT:
        return GAMMA * math.log2(x + BETA) + DELTA
    if x >= R0:
        return C * (x - R0) ** 2
    return 0.0


def apple_log_decode(y):
    if y >= YT:
        return 2.0 ** ((y - DELTA) / GAMMA) - BETA
    if y > 0.0:
        return R0 + math.sqrt(y / C)
    return R0


REC2020_TO_709 = [
    [1.6605, -0.5876, -0.0728],
    [-0.1246, 1.1329, -0.0083],
    [-0.0182, -0.1006, 1.1187],
]


def tonemap(x):
    x = max(x, 0.0) * 0.8
    return min(max((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14), 0.0), 1.0)


def srgb(v):
    return v * 12.92 if v < 0.0031308 else 1.055 * v ** (1 / 2.4) - 0.055


def gamma24(v):
    return v ** (1 / 2.4)


def transform(rgb_log, encode):
    lin = [apple_log_decode(c) for c in rgb_log]
    out = []
    for row in REC2020_TO_709:
        v = sum(row[i] * lin[i] for i in range(3))
        out.append(encode(tonemap(v)))
    return out


def write_cube(path, size, encode, title):
    with open(path, "w") as f:
        f.write(f'TITLE "{title}"\n')
        f.write("# Generated by color_science/generate_applelog_lut.py\n")
        f.write(f"LUT_3D_SIZE {size}\nDOMAIN_MIN 0.0 0.0 0.0\nDOMAIN_MAX 1.0 1.0 1.0\n")
        for b in range(size):
            for g in range(size):
                for r in range(size):
                    o = transform([r / (size - 1), g / (size - 1), b / (size - 1)], encode)
                    f.write(f"{o[0]:.6f} {o[1]:.6f} {o[2]:.6f}\n")


def self_test():
    for x in [0.0, 0.005, 0.01, 0.18, 1.0, 8.0]:
        assert abs(apple_log_decode(apple_log_encode(x)) - x) < 1e-6, x
    assert abs(apple_log_encode(0.18) - 0.4883) < 1e-3
    grey = transform([apple_log_encode(0.18)] * 3, srgb)
    assert 0.45 < grey[0] < 0.52, grey


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--size", type=int, default=33)
    args = ap.parse_args()
    self_test()
    here = os.path.dirname(os.path.abspath(__file__))
    write_cube(os.path.join(here, "AppleLog_to_Rec709_Gamma24.cube"), args.size, gamma24,
               "Vesper Cine Apple Log to Rec.709 (Gamma 2.4)")
    write_cube(os.path.join(here, "AppleLog_to_Rec709_sRGB.cube"), args.size, srgb,
               "Vesper Cine Apple Log to Rec.709 (sRGB viewfinder match)")
    print("Apple Log reference points:")
    for label, x in [("black", 0.0), ("18% grey", 0.18), ("sensor clip @5.5 stops", 0.18 * 2 ** 5.5), ("max", 12.0)]:
        print(f"  {label:<24} linear {x:7.3f} -> Apple Log {apple_log_encode(x):.4f}")
