#pragma once
#include <cstdint>
#include <sys/types.h>
typedef enum { ACAMERA_OK = 0 } camera_status_t;
struct ACameraMetadata; typedef struct ACameraMetadata ACameraMetadata;
typedef struct { int32_t numerator, denominator; } ACameraMetadata_rational;
typedef struct { uint32_t tag; uint8_t type; uint32_t count; union { const uint8_t* u8; const int32_t* i32; const float* f; const int64_t* i64; const double* d; const ACameraMetadata_rational* r; } data; } ACameraMetadata_const_entry;
camera_status_t ACameraMetadata_getConstEntry(const ACameraMetadata*, uint32_t, ACameraMetadata_const_entry*);
void ACameraMetadata_free(ACameraMetadata*);
enum : uint32_t { ACAMERA_SENSOR_INFO_WHITE_LEVEL=1, ACAMERA_SENSOR_INFO_COLOR_FILTER_ARRANGEMENT, ACAMERA_SENSOR_ORIENTATION, ACAMERA_SENSOR_INFO_ACTIVE_ARRAY_SIZE,
 ACAMERA_SENSOR_BLACK_LEVEL_PATTERN, ACAMERA_LENS_INFO_SHADING_MAP_SIZE, ACAMERA_SENSOR_INFO_LENS_SHADING_APPLIED, ACAMERA_SENSOR_INFO_TIMESTAMP_SOURCE,
 ACAMERA_SENSOR_INFO_EXPOSURE_TIME_RANGE, ACAMERA_SENSOR_INFO_SENSITIVITY_RANGE, ACAMERA_LENS_INFO_MINIMUM_FOCUS_DISTANCE, ACAMERA_SCALER_AVAILABLE_STREAM_CONFIGURATIONS,
 ACAMERA_SCALER_AVAILABLE_MIN_FRAME_DURATIONS, ACAMERA_SENSOR_COLOR_TRANSFORM1, ACAMERA_SENSOR_COLOR_TRANSFORM2, ACAMERA_SENSOR_FORWARD_MATRIX1, ACAMERA_SENSOR_FORWARD_MATRIX2,
 ACAMERA_SENSOR_CALIBRATION_TRANSFORM1, ACAMERA_SENSOR_CALIBRATION_TRANSFORM2, ACAMERA_SENSOR_REFERENCE_ILLUMINANT1, ACAMERA_SENSOR_REFERENCE_ILLUMINANT2,
 ACAMERA_LENS_FACING, ACAMERA_INFO_SUPPORTED_HARDWARE_LEVEL, ACAMERA_CONTROL_MODE, ACAMERA_CONTROL_AE_MODE, ACAMERA_CONTROL_AWB_MODE, ACAMERA_CONTROL_AF_MODE,
 ACAMERA_CONTROL_VIDEO_STABILIZATION_MODE, ACAMERA_NOISE_REDUCTION_MODE, ACAMERA_EDGE_MODE, ACAMERA_SHADING_MODE, ACAMERA_STATISTICS_LENS_SHADING_MAP_MODE,
 ACAMERA_LENS_OPTICAL_STABILIZATION_MODE, ACAMERA_LENS_FOCUS_DISTANCE, ACAMERA_SENSOR_FRAME_DURATION, ACAMERA_SENSOR_EXPOSURE_TIME, ACAMERA_SENSOR_SENSITIVITY,
 ACAMERA_CONTROL_AE_TARGET_FPS_RANGE, ACAMERA_SENSOR_TIMESTAMP, ACAMERA_SENSOR_DYNAMIC_BLACK_LEVEL, ACAMERA_SENSOR_DYNAMIC_WHITE_LEVEL, ACAMERA_STATISTICS_LENS_SHADING_MAP,
 ACAMERA_SENSOR_NEUTRAL_COLOR_POINT };
enum { ACAMERA_SENSOR_INFO_TIMESTAMP_SOURCE_REALTIME = 1, ACAMERA_LENS_FACING_BACK = 1, ACAMERA_CONTROL_MODE_OFF = 0, ACAMERA_CONTROL_AE_MODE_OFF = 0,
 ACAMERA_CONTROL_AWB_MODE_OFF = 0, ACAMERA_CONTROL_AF_MODE_OFF = 0, ACAMERA_CONTROL_VIDEO_STABILIZATION_MODE_OFF = 0, ACAMERA_NOISE_REDUCTION_MODE_OFF = 0,
 ACAMERA_EDGE_MODE_OFF = 0, ACAMERA_SHADING_MODE_FAST = 1, ACAMERA_STATISTICS_LENS_SHADING_MAP_MODE_ON = 1, ACAMERA_LENS_OPTICAL_STABILIZATION_MODE_ON = 1,
 ACAMERA_LENS_OPTICAL_STABILIZATION_MODE_OFF = 0 };
