#!/usr/bin/env bash
# Regenerates the embedded SPIR-V headers. Run after editing any .comp/.glsl:
#   android/app/src/main/cpp/shaders/compile_shaders.sh
# Needs glslangValidator (Vulkan SDK, `apt install glslang-tools`, or the NDK's shader-tools).
set -euo pipefail
cd "$(dirname "$0")"
for name in unpack green align clean render; do
  glslangValidator -V --target-env vulkan1.1 "$name.comp" -o "/tmp/vesper_$name.spv" >/dev/null
  python3 - "$name" "/tmp/vesper_$name.spv" > "${name}_spv.h" <<'PY'
import struct, sys
name, path = sys.argv[1], sys.argv[2]
data = open(path, 'rb').read()
words = struct.unpack('<%dI' % (len(data) // 4), data)
print('// Generated by compile_shaders.sh from %s.comp — do not edit.' % name)
print('#pragma once')
print('#include <cstdint>')
print('static const uint32_t k%sSpv[] = {' % name.capitalize())
for i in range(0, len(words), 8):
    print('    ' + ', '.join('0x%08x' % w for w in words[i:i + 8]) + ',')
print('};')
PY
done
# Variants: <header name> <symbol> <source> <defines...>
variant() {
  local out=$1 sym=$2 src=$3; shift 3
  glslangValidator -V --target-env vulkan1.1 "$@" $src.comp -o /tmp/vesper_$out.spv >/dev/null
  python3 - "$sym" /tmp/vesper_$out.spv "$src" "$*" > ${out}_spv.h <<'PY'
import struct, sys
name, path, src, defs = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
data = open(path, 'rb').read()
words = struct.unpack('<%dI' % (len(data) // 4), data)
print('// Generated by compile_shaders.sh from %s.comp (%s) — do not edit.' % (src, defs))
print('#pragma once')
print('#include <cstdint>')
print('static const uint32_t k%sSpv[] = {' % name)
for i in range(0, len(words), 8):
    print('    ' + ', '.join('0x%08x' % w for w in words[i:i + 8]) + ',')
print('};')
PY
}
# green.comp: RGBA16F storage fallback, and 16-bit arithmetic (HQ_FP16).
variant green_rgba GreenRgba green -DGREEN_RGBA16F
variant green_fp16 GreenFp16 green -DHQ_FP16
variant green_rgba_fp16 GreenRgbaFp16 green -DGREEN_RGBA16F -DHQ_FP16
# GPU benchmark experiments (opt-in, VulkanEngine::setExperiments) and probes
# (partial passes whose cost shows where a pass spends its time).
variant green_fp16_probe1 GreenFp16Probe1 green -DHQ_FP16 -DHQ_PROBE=1
variant green_fp16_probe2 GreenFp16Probe2 green -DHQ_FP16 -DHQ_PROBE=2
variant green_fp16_exact GreenFp16Exact green -DHQ_FP16 -DHQ_EXACT_SHADING
variant green_fp16_wide GreenFp16Wide green -DHQ_FP16 -DHQ_WIDE
variant render_wg16x8 RenderWg16x8 render -DRENDER_WG_X=16 -DRENDER_WG_Y=8
variant render_wg16x16 RenderWg16x16 render -DRENDER_WG_X=16 -DRENDER_WG_Y=16
variant clean_wg16x16 CleanWg16x16 clean -DCLEAN_WG_X=16 -DCLEAN_WG_Y=16
variant clean_wg8x8 CleanWg8x8 clean -DCLEAN_WG_X=8 -DCLEAN_WG_Y=8
echo "SPIR-V headers regenerated"
