#!/usr/bin/env bash
# Regenerates the embedded SPIR-V headers. Run after editing any .comp/.glsl:
#   android/app/src/main/cpp/shaders/compile_shaders.sh
# Needs glslangValidator (Vulkan SDK, `apt install glslang-tools`, or the NDK's shader-tools).
set -euo pipefail
cd "$(dirname "$0")"
for name in unpack green align clean render; do
  glslangValidator -V --target-env vulkan1.1 "$name.comp" -o "/tmp/vesper_$name.spv" >/dev/null
  python3 - "$name" "/tmp/vesper_$name.spv" > "${name}_spv.h" <<'PY'
import struct, sys
name, path = sys.argv[1], sys.argv[2]
data = open(path, 'rb').read()
words = struct.unpack('<%dI' % (len(data) // 4), data)
print('// Generated by compile_shaders.sh from %s.comp — do not edit.' % name)
print('#pragma once')
print('#include <cstdint>')
print('static const uint32_t k%sSpv[] = {' % name.capitalize())
for i in range(0, len(words), 8):
    print('    ' + ', '.join('0x%08x' % w for w in words[i:i + 8]) + ',')
print('};')
PY
done
# Fallback variant of green.comp for GPUs without R16F storage images.
glslangValidator -V --target-env vulkan1.1 -DGREEN_RGBA16F green.comp -o /tmp/vesper_green_rgba.spv >/dev/null
python3 - GreenRgba /tmp/vesper_green_rgba.spv > green_rgba_spv.h <<'PY'
import struct, sys
name, path = sys.argv[1], sys.argv[2]
data = open(path, 'rb').read()
words = struct.unpack('<%dI' % (len(data) // 4), data)
print('// Generated by compile_shaders.sh from green.comp (-DGREEN_RGBA16F) — do not edit.')
print('#pragma once')
print('#include <cstdint>')
print('static const uint32_t k%sSpv[] = {' % name)
for i in range(0, len(words), 8):
    print('    ' + ', '.join('0x%08x' % w for w in words[i:i + 8]) + ',')
print('};')
PY
echo "SPIR-V headers regenerated"
